name: eslint

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    
    steps:
    - name: npm install
    #  Install project
    run: make install
    
    - name: Run linter
    run: make lint
    
      
